framework:
    rate_limiter:
        anonymous_api:
            policy: 'token_bucket'
            limit: 100
            rate:
                interval: '1 minute'
                amount: 100

        authenticated_api:
            policy: 'token_bucket'
            limit: 1000
            rate:
                interval: '1 minute'
                amount: 1000
